heat_template_version: '2013-05-23'

description: >
  This template instantiates the Bioplatforms Australia Training Platform VMs.

parameters:
  key_name:
    type: string
    label: Key Name
    description:
      Name of an existing key pair to enable SSH access to the instance.
  instance_type:
    type: string
    label: Instance Type
    description:
      Size of the instance to be created.
    default: m1.small
    constraints:
      - allowed_values: 
        - m1.small 
        - m1.medium 
        - m1.large
        - m1.xlarge 
        - m1.xxlarge
        description:
          Must be a valid NeCTAR Flavour.
  image_id:
    type: string
    label: Image ID
    description:
      ID of the NeCTAR image to be used for the instance.
    default: 'd0f3c4fd-41db-4836-924b-391fb252dd5d'
  availability_zone:
    type: string
    label: Availability Zone
    description: 
      The NeCTAR availability zone where to launch the instance.
    default: monash-01
    constraints:
      - allowed_values: 
        - monash-01
        - melbourne-qh2
        - melbourne-np 
        - qld
        - NCI 
        - sa 
        - tasmania
        description:
          Must be a valid NeCTAR Availability Zone.
  UbuntuPassword:
    type: string
    label: Ubuntu Password
    description: Password for the local ubuntu user
    hidden: True 
    constraints:
      - length: { min: 8, max: 12 }
        description:
          Password length must be between 8 and 12 characters.
      - allowed_pattern: "[a-zA-Z0-9]+"
        description:
          Password must consist of characters and numbers only.
  TraineePassword:
    type: string
    label: Trainee Password
    description: Password of the local trainee user
    hidden: True 
    constraints:
      - length: { min: 8, max: 12 }
        description:
          Password length must be between 8 and 12 characters.
      - allowed_pattern: "[a-zA-Z0-9]+"
        description:
          Password must consist of characters and numbers only.
  
resources:
  ngs_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      flavor: { get_param: instance_type }
      image: { get_param: image_id }
      availability_zone: { get_param: availability_zone }
      user_data:
        str_replace: 
          template: |
            #!/bin/bash
            echo "Bootstrapping NGS Instance ..."
            echo "Setting password for ubuntu user ..."
            echo -e "ubuntu:${ubuntu_password}" | chpasswd
            echo "Setting password for ${trainee_username} ..."
            echo -e "${trainee_username}:${trainee_password}" | chpasswd
          params:
            $ubuntu_password: { get_param: UbuntuPassword } 
            $trainee_password: { get_param: TraineePassword } 

outputs:
  instance_ip:
    description: The IP address of the deployed instance.
    value: { get_attr: [my_instance, first_address] }
