HeatTemplateFormatVersion: '2012-12-12'

Description: "This template instantiates the Bioplatforms Australia Training
  Platform. This will launch a single virtual machine on the NeCTAR Research
  Cloud using the latest virtual machine image."

Parameters:
  KeyName:
    Description: "Name of an existing key pair to access the instance."
    Type: "String"
  InstanceType:
    Description: "Size of the instance to be created."
    Type: "String"
    Default: "m1.small"
    AllowedValues: 
      - "m1.small" 
      - "m1.medium" 
      - "m1.large"
      - "m1.xlarge" 
      - "m1.xxlarge"
  ImageName:
    Description: "ID of the NeCTAR image to be used for the instance."
    Type: "String"
    Default: "NGSTrainingV1.4"
    AllowedValues:
      - "NGSTrainingV1.4"
  AvailabilityZone:
    Description: "NeCTAR availability zone where to launch the instance."
    Type: "String"
    Default: "monash-01"
    AllowedValues: 
      - "monash-01"
      - "melbourne-qh2"
      - "melbourne-np"
      - "qld"
      - "NCI"
      - "sa"
      - "tasmania"
  UbuntuPassword:
    Description: "Password for the local ubuntu user."
    Type: "String"

Mappings:
  NGSImageName:
    "NGSTrainingV1.4": { NGSImageID: 1b6bed46-6824-47e1-8f05-c0c590108305 }

Resources:
  NGSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable ssh (port 22) access"
      SecurityGroupIngress:
        - IpProtocol: "icmp"
          FromPort: "-1"
          ToPort: "-1"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
      
  NGSInstance:
    Type: "AWS::EC2::Instance"
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              freenx-server: []
    Properties:
      ImageId:
        Fn::FindInMap:
          - NGSImageName
          - { Ref: ImageName}
          - NGSImageID
      InstanceType: { Ref: InstanceType }
      KeyName: { Ref: KeyName }
      SecurityGroups:
        - { Ref: NGSSecurityGroup }
      KeyName: { Ref: KeyName }
      AvailabilityZone: { Ref: AvailabilityZone }
      UserData:
        Fn::Base64:
          Fn::Replace:
            - MyUbuntuPassword: { Ref: UbuntuPassword }
            - |
              #!/bin/bash
              echo "Bootstrapping NGS Instance ..."
              echo "Setting password for ubuntu user ..."
              echo -e "ubuntu:MyUbuntuPassword" | chpasswd
              echo "Download relevant datasets, tools from NeCTAR Object Storage ..."
              cd /tmp/
              wget https://raw.githubusercontent.com/BPA-CSIRO-Workshops/btp-catalogue/master/ngs-workshop/ngs-data.sh
              bash ngs-data.sh
              echo "Installing required packages ..."
